// Profile / song-marker borders (the weekly-challenge rewards).
//
// Each border is a set of small SVG files in public/borders, generated by
// tools/borders/generate_borders.py:  <key>-<circle|square>-<1|2>.svg
//   circle = wraps a round profile picture, square = wraps an ocean song marker
//   1 / 2  = two layers that move on different rhythms (so the motion feels organic)
// <key> is the reward's css_class from the `rewards` table.

export const BORDERS: Record<string, { name: string }> = {
  'bubble-ring': { name: 'Bubble Ring' },
  'sea-sparkle': { name: 'Sea Sparkle' },
  'pearl-strand': { name: 'Pearl Strand' },
  'kelp-wreath': { name: 'Kelp Wreath' },
  'coral-reef': { name: 'Coral Reef' },
  'starfish-shells': { name: 'Starfish & Shells' },
  skeletons: { name: 'Skeletons' },
  'dino-eggs': { name: 'Dino Eggs' },
};

export type BorderShape = 'circle' | 'square';

export function isBorderKey(key: string | null | undefined): key is string {
  return !!key && Object.prototype.hasOwnProperty.call(BORDERS, key);
}

export function borderLayerUrl(key: string, shape: BorderShape, layer: 1 | 2): string {
  return `/borders/${key}-${shape}-${layer}.svg`;
}

// The artwork is drawn on a 400-unit canvas whose middle 184 units are the
// picture itself, so the art box is this many times bigger than the picture.
export const BORDER_ART_SCALE = 400 / 184;

// The animation, as plain formulas of time `t` (seconds). The DOM version
// (CSS keyframes in index.css, .wl-border-*) and the canvas version (ocean
// markers, useOceanCanvas.ts) both follow these, so they match. Keep the
// durations in sync with index.css.
//   breathing: layer 1 swells to +7.5% and settles every 7s; layer 2 does the
//              opposite on a 9s beat.
//   circles  : the layers spin very slowly, in opposite directions (120s / 180s per turn).
//   squares  : a full spin would sweep through the corners of the song marker,
//              so they rock gently back and forth instead (11s / 15s).
const wave = (t: number, period: number) => 0.5 - 0.5 * Math.cos((2 * Math.PI * t) / period); // 0 -> 1 -> 0

export function borderMotion(shape: BorderShape, layer: 1 | 2, t: number): { scale: number; rotateDeg: number } {
  const scale = layer === 1 ? 1 + 0.075 * wave(t, 7) : 1.03 - 0.03 * wave(t, 9);
  let rotateDeg: number;
  if (shape === 'circle') rotateDeg = layer === 1 ? (360 * t) / 120 : (-360 * t) / 180;
  else rotateDeg = layer === 1 ? -7 * Math.cos((2 * Math.PI * t) / 11) : 6 * Math.cos((2 * Math.PI * t) / 15);
  return { scale, rotateDeg };
}
